### ISSUE TITLE
[REQ] fix license on GH

### ISSUE THREAD

**Issue by MarcoRavich** [parthdomadia/VideoEditor#1]
Hi there, 1st of all thanks for your awesome work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [VIDEO](https://github.com/forart/HyMPS#-1) \ [AI-based](https://github.com/forart/HyMPS/blob/main/AIvideo.md#--) \ [Editing subsection](https://github.com/forart/HyMPS/blob/main/AIvideo.md#editing-)), can you please add the license to it ?

Expliciting the licensing terms is extremely important to let other devs (and not only) better/faster understand how to reuse/adapt/modify your code in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/parthdomadia/VideoEditor/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/parthdomadia/VideoEditor/?label=LICENSE)

Anyway you can easily set a standardized one through the GH's license wizard tool.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by parthdomadia** [comment]
Have added a new license to the repo, thank you for pointing this out and for using this repo!

**Comment by MarcoRavich** [comment]
Thanks a lot.

Hope HyMPS may help your project "evolvution" by let you establish some kind of collaboration with other projects' devs.

Thanks again.
